name: rbfe
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip

  # Core scientific stack
  - numpy
  - scipy
  - pandas
  - matplotlib

  # OpenMM + alchemy
  - openmm=8.1.*
  - openmmtools=0.25.3
  - pymbar

  # Chemistry
  - rdkit
  - openff-toolkit
  - openmmforcefields
  - ambertools

  # Optional viz
  - streamlit
  - plotly

  # If needed, uncomment one line below (depends on cluster setup):
  # - cudatoolkit=11.8

